scope: store signals and scopes in different namespaces
In the data structure used to represent the signal scopes, the sub-scopes
and the signal IDs were stored in the same BTreeMap which led to name
conflicts in some cases. For example:

    $ cat input.vcd
    ...
    $scope module top $end
        $var wire 1 A foo $end
        $scope module A $end
    ...
    $ dwfv input.vcd
    thread '<unnamed>' panicked at 'Specified path is a signal, not a scope', dwfv-0.4.0/src/signaldb/scope.rs:49:18
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Fixes #9

Signed-off-by: Pierre Surply <pierre.surply@gmail.com>